apiVersion: v1
kind: Service
metadata:
  name: newspapers-app #It selects the Pods to expose according to their labels.
spec:
  selector:
    app: newspapers-app
  ports:
    - port: 80
      targetPort: 3001
  type: LoadBalancer #the type is LoadBalancer, which makes the exposed Pods accessible from outside the cluster. default Service type is ClusterIP, which makes the exposed Pods only accessible from within the cluster.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newspapers-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newspapers-app #abel to belong to this Deployment resource
  template:
    metadata:
      labels:
        app: newspapers-app #defines a label for the Pods
    spec:
      containers:
        - name: newspapers-app
          image: phanthaiduong22/newspapers:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: DB_NAME
              value: newspapers
          imagePullPolicy: Always #forces the Docker image to be downloaded, even if it was already downloaded.
# To expose your app, you need a Service.